### PR TITLE
Be more permissive with faraday and faraday_middleware dependencies

### PR DESCRIPTION
**Pull request by jpawlyn**
With the 1.0 release of faraday and faraday_middleware, perhaps the gemspec can be more permissive with these 2 dependencies thereby enabling the faraday gems and other gems depending on them to be updated?

### CODE REVIEW

**Comment by iggant** [comment]
Yes this is very important, because faraday 0.15 cause a lot of warnings with ruby 2.7

**Comment by jpawlyn** [comment]
> Yes this is very important, because faraday 0.15 cause a lot of warnings with ruby 2.7

Would it be possible to bump to `>= 0.16` instead perhaps?

**Comment by iggant** [comment]
> > Yes this is very important, because faraday 0.15 cause a lot of warnings with ruby 2.7
> 
> Would it be possible to bump to `>= 0.16` instead perhaps?

Anything > 0.15 would be nice

**Comment by jpawlyn** [comment]
@iggant Any good?

**Comment by iggant** [comment]
Actually yes, 
I don't understand why test fail

**Comment by wolfadex** [comment]
The [19.0.0.20220420](https://rubygems.org/gems/square.rb) release includes updated versions of Faraday (as well as additional features and dropping support for Ruby 2.5). I hope this helps you with your work. Please let us know if it is still holding you back, and if you have any API related questions I hop you'll reach out in our [Slack](https://buildwithsquare.slack.com/ssb/redirect) or [Forums](https://developer.squareup.com/forums/).

**Pull request closed without merging**
